#!/usr/bin/env python3
"""
Phylogenetic Tree Comparison Utility

This module provides tools to compare phylogenetic trees generated by biomodelml
with the true evolutionary tree. It calculates various metrics including:
- Robinson-Foulds distance (topological similarity)
- Branch length correlation
- Monophyly preservation
"""

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple, Set
import sys

try:
    from ete3 import Tree
except ImportError:
    print("Error: ete3 is required for tree comparison")
    print("Install with: pip install ete3")
    sys.exit(1)


@dataclass
class TreeComparisonMetrics:
    """Metrics for comparing two phylogenetic trees"""
    algorithm_name: str
    robinson_foulds_distance: float
    normalized_rf_distance: float
    branch_length_correlation: float
    common_bipartitions: int
    total_bipartitions: int
    topology_match: bool
    
    def __str__(self):
        import math
        
        # Handle NaN correlation
        if math.isnan(self.branch_length_correlation):
            corr_str = "N/A (no branch length variation)"
        else:
            corr_str = f"{self.branch_length_correlation:.3f}"
        
        return (
            f"\n{self.algorithm_name}\n"
            f"{'-' * len(self.algorithm_name)}\n"
            f"Robinson-Foulds Distance: {self.robinson_foulds_distance:.0f}\n"
            f"Normalized RF Distance: {self.normalized_rf_distance:.3f} "
            f"({'Perfect match!' if self.normalized_rf_distance == 0 else 'some differences'})\n"
            f"Branch Length Correlation: {corr_str}\n"
            f"Common Bipartitions: {self.common_bipartitions}/{self.total_bipartitions}\n"
            f"Topology Match: {'✓ Yes' if self.topology_match else '✗ No'}"
        )


def load_tree(newick_path: Path) -> Tree:
    """Load a phylogenetic tree from Newick format"""
    try:
        tree = Tree(str(newick_path), format=1)
        return tree
    except Exception as e:
        print(f"Error loading tree from {newick_path}: {e}")
        sys.exit(1)


def inspect_tree_structure(tree: Tree) -> dict:
    """
    Inspect the structure of a tree and return diagnostic information
    
    Returns:
        Dictionary with tree statistics including branch length information
    """
    leaves = tree.get_leaf_names()
    branch_lengths = []
    
    # Collect all branch lengths (excluding root)
    for node in tree.traverse():
        if not node.is_root():
            branch_lengths.append(node.dist)
    
    # Check if branch lengths are meaningful
    has_branch_lengths = len(branch_lengths) > 0
    all_same = len(set(branch_lengths)) == 1 if branch_lengths else True
    
    # Check for polytomies (nodes with >2 children)
    polytomies = []
    for node in tree.traverse():
        if not node.is_leaf() and len(node.children) > 2:
            polytomies.append(len(node.children))
    
    info = {
        'num_leaves': len(leaves),
        'num_internal_nodes': len([n for n in tree.traverse() if not n.is_leaf()]),
        'has_branch_lengths': has_branch_lengths,
        'all_branch_lengths_same': all_same,
        'has_polytomies': len(polytomies) > 0,
        'polytomies': polytomies,
        'branch_length_stats': {}
    }
    
    if has_branch_lengths:
        import numpy as np
        info['branch_length_stats'] = {
            'min': float(np.min(branch_lengths)),
            'max': float(np.max(branch_lengths)),
            'mean': float(np.mean(branch_lengths)),
            'std': float(np.std(branch_lengths))
        }
    
    return info


def get_bipartitions(tree: Tree) -> Set[frozenset]:
    """
    Get all bipartitions (splits) defined by the tree
    
    A bipartition is a division of taxa into two groups defined by an edge
    """
    bipartitions = set()
    
    # Get all leaf names
    all_leaves = set(tree.get_leaf_names())
    
    # For each internal node, create a bipartition
    for node in tree.traverse("postorder"):
        if not node.is_leaf() and not node.is_root():
            # Get leaves on one side of the split
            descendant_leaves = frozenset(node.get_leaf_names())
            # Other side is the complement
            if len(descendant_leaves) > 0 and len(descendant_leaves) < len(all_leaves):
                # Store the smaller side to make comparison easier
                if len(descendant_leaves) <= len(all_leaves) / 2:
                    bipartitions.add(descendant_leaves)
                else:
                    bipartitions.add(frozenset(all_leaves - descendant_leaves))
    
    return bipartitions


def calculate_robinson_foulds(tree1: Tree, tree2: Tree) -> Tuple[float, float]:
    """
    Calculate Robinson-Foulds distance between two trees
    
    Returns:
        Tuple of (rf_distance, normalized_rf_distance)
        normalized_rf_distance is in range [0, 1] where 0 is identical
    """
    # Get leaf sets
    leaves1 = set(tree1.get_leaf_names())
    leaves2 = set(tree2.get_leaf_names())
    
    # Trees must have the same taxa
    if leaves1 != leaves2:
        common_leaves = leaves1 & leaves2
        if len(common_leaves) < 3:
            return float('inf'), 1.0
        
        # Prune trees to common leaves
        tree1 = tree1.copy()
        tree2 = tree2.copy()
        tree1.prune(common_leaves)
        tree2.prune(common_leaves)
    
    # Get bipartitions
    bipartitions1 = get_bipartitions(tree1)
    bipartitions2 = get_bipartitions(tree2)
    
    # RF distance is the number of bipartitions in one tree but not the other
    symmetric_difference = len(bipartitions1.symmetric_difference(bipartitions2))
    
    # Normalize by the maximum possible RF distance
    max_rf = 2 * (len(leaves1) - 3)  # Maximum for binary trees
    if max_rf == 0:
        normalized_rf = 0.0
    else:
        normalized_rf = symmetric_difference / max_rf
    
    return symmetric_difference, normalized_rf


def calculate_branch_length_correlation(tree1: Tree, tree2: Tree) -> float:
    """
    Calculate Pearson correlation of branch lengths between two trees
    
    Only considers branches that exist in both trees (same bipartition)
    """
    # Get bipartitions with their branch lengths
    def get_bipartition_lengths(tree):
        bp_lengths = {}
        all_leaves = set(tree.get_leaf_names())
        
        for node in tree.traverse("postorder"):
            if not node.is_leaf() and not node.is_root():
                descendant_leaves = frozenset(node.get_leaf_names())
                if len(descendant_leaves) > 0 and len(descendant_leaves) < len(all_leaves):
                    # Use the smaller side as key
                    if len(descendant_leaves) <= len(all_leaves) / 2:
                        key = descendant_leaves
                    else:
                        key = frozenset(all_leaves - descendant_leaves)
                    bp_lengths[key] = node.dist
        
        return bp_lengths
    
    bp_lengths1 = get_bipartition_lengths(tree1)
    bp_lengths2 = get_bipartition_lengths(tree2)
    
    # Find common bipartitions
    common_bp = set(bp_lengths1.keys()) & set(bp_lengths2.keys())
    
    if len(common_bp) < 2:
        return 0.0
    
    # Get paired branch lengths
    lengths1 = [bp_lengths1[bp] for bp in common_bp]
    lengths2 = [bp_lengths2[bp] for bp in common_bp]
    
    # Calculate Pearson correlation
    try:
        import numpy as np
        correlation = np.corrcoef(lengths1, lengths2)[0, 1]
        # Return NaN if there's no variation (all values identical)
        return correlation
    except (ImportError, ValueError):
        # Fallback: simple correlation without numpy
        n = len(lengths1)
        mean1 = sum(lengths1) / n
        mean2 = sum(lengths2) / n
        
        numerator = sum((x - mean1) * (y - mean2) for x, y in zip(lengths1, lengths2))
        denom1 = sum((x - mean1) ** 2 for x in lengths1) ** 0.5
        denom2 = sum((y - mean2) ** 2 for y in lengths2) ** 0.5
        
        if denom1 == 0 or denom2 == 0:
            # No variation in branch lengths - return NaN
            return float('nan')
        
        return numerator / (denom1 * denom2)


def compare_trees(true_tree_path: Path, inferred_tree_path: Path) -> TreeComparisonMetrics:
    """
    Compare a true phylogenetic tree with an inferred tree
    
    Returns metrics quantifying the similarity
    """
    # Extract algorithm name from filename
    algorithm_name = inferred_tree_path.stem.replace('.nw', '')
    
    # Load trees
    true_tree = load_tree(true_tree_path)
    inferred_tree = load_tree(inferred_tree_path)
    
    # Calculate metrics
    rf_dist, norm_rf = calculate_robinson_foulds(true_tree, inferred_tree)
    bl_corr = calculate_branch_length_correlation(true_tree, inferred_tree)
    
    # Get bipartition counts
    true_bps = get_bipartitions(true_tree)
    inferred_bps = get_bipartitions(inferred_tree)
    common_bps = len(true_bps & inferred_bps)
    total_bps = len(true_bps | inferred_bps)
    
    # Topology match if RF distance is 0
    topology_match = (rf_dist == 0)
    
    return TreeComparisonMetrics(
        algorithm_name=algorithm_name,
        robinson_foulds_distance=rf_dist,
        normalized_rf_distance=norm_rf,
        branch_length_correlation=bl_corr,
        common_bipartitions=common_bps,
        total_bipartitions=total_bps,
        topology_match=topology_match
    )


def render_tree(tree: Tree, output_path: Path, title: str = None):
    """
    Render a phylogenetic tree to an image file
    
    Uses matplotlib for visualization
    """
    try:
        import matplotlib.pyplot as plt
        import matplotlib.patches as mpatches
        from matplotlib.lines import Line2D
        
        fig, ax = plt.subplots(figsize=(12, 8))
        
        # Get tree layout coordinates
        def get_layout(node, x=0, y=0, y_step=1):
            """Calculate x,y positions for tree nodes"""
            if node.is_leaf():
                return {node.name: (x + node.dist, y)}, y + y_step
            
            coords = {}
            current_y = y
            child_ys = []
            
            for child in node.children:
                child_coords, current_y = get_layout(child, x + node.dist, current_y, y_step)
                coords.update(child_coords)
                child_ys.append(list(child_coords.values())[0][1])
            
            # Position internal node at midpoint of children
            node_y = (min(child_ys) + max(child_ys)) / 2
            coords[id(node)] = (x, node_y)
            
            return coords, current_y
        
        # Get coordinates
        tree_copy = tree.copy()
        tree_copy.dist = 0  # Root has no branch length
        coords, _ = get_layout(tree_copy)
        
        # Draw branches
        for node in tree_copy.traverse():
            if node.is_root():
                continue
            
            parent = node.up
            node_pos = coords.get(node.name if node.is_leaf() else id(node))
            parent_pos = coords.get(id(parent))
            
            if node_pos and parent_pos:
                # Horizontal line
                ax.plot([parent_pos[0], node_pos[0]], [node_pos[1], node_pos[1]], 
                       'k-', linewidth=1.5)
                # Vertical line
                ax.plot([parent_pos[0], parent_pos[0]], [parent_pos[1], node_pos[1]], 
                       'k-', linewidth=1.5)
                
                # Add branch length label
                mid_x = (parent_pos[0] + node_pos[0]) / 2
                ax.text(mid_x, node_pos[1] + 0.1, f'{node.dist:.2f}', 
                       fontsize=8, ha='center', color='#666')
        
        # Draw nodes and labels
        for node in tree_copy.traverse():
            pos = coords.get(node.name if node.is_leaf() else id(node))
            if pos:
                if node.is_leaf():
                    ax.plot(pos[0], pos[1], 'o', color='#0066cc', markersize=8)
                    ax.text(pos[0] + 0.05, pos[1], node.name, 
                           fontsize=10, va='center', weight='bold')
                else:
                    ax.plot(pos[0], pos[1], 'o', color='#666', markersize=6)
        
        # Formatting
        if title:
            ax.set_title(title, fontsize=14, fontweight='bold', pad=20)
        ax.set_xlabel('Branch Length', fontsize=11)
        ax.set_ylabel('Taxa', fontsize=11)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.spines['left'].set_visible(False)
        ax.set_yticks([])
        ax.grid(axis='x', alpha=0.3, linestyle='--')
        
        plt.tight_layout()
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        plt.close()
        
        print(f"  Tree visualization saved to: {output_path}")
        
    except Exception as e:
        print(f"  Warning: Could not render tree: {e}")


def visualize_comparison(true_tree: Tree, inferred_tree: Tree, output_path: Path):
    """
    Create a visual comparison of two trees
    
    Saves side-by-side tree images
    """
    try:
        import matplotlib.pyplot as plt
        from matplotlib.patches import Rectangle
        
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8))
        
        # Render trees (simplified - ete3 has better rendering)
        ax1.set_title("True Phylogeny", fontsize=14, fontweight='bold')
        ax1.text(0.5, 0.5, f"Leaves: {len(true_tree.get_leaf_names())}\n\n"
                 f"{', '.join(sorted(true_tree.get_leaf_names()))}",
                 ha='center', va='center', fontsize=10)
        ax1.axis('off')
        
        ax2.set_title("Inferred Phylogeny", fontsize=14, fontweight='bold')
        ax2.text(0.5, 0.5, f"Leaves: {len(inferred_tree.get_leaf_names())}\n\n"
                 f"{', '.join(sorted(inferred_tree.get_leaf_names()))}",
                 ha='center', va='center', fontsize=10)
        ax2.axis('off')
        
        plt.tight_layout()
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        plt.close()
        
        print(f"Visualization saved to: {output_path}")
    except ImportError:
        print("Note: matplotlib not available for visualization")


def main():
    parser = argparse.ArgumentParser(
        description="Compare phylogenetic trees"
    )
    parser.add_argument(
        'true_tree',
        type=Path,
        help='Path to true phylogenetic tree (Newick format)'
    )
    parser.add_argument(
        'inferred_trees',
        type=Path,
        nargs='+',
        help='Path(s) to inferred phylogenetic tree(s) (Newick format)'
    )
    parser.add_argument(
        '--output', '-o',
        type=Path,
        help='Output file for comparison report (default: print to stdout)'
    )
    parser.add_argument(
        '--visualize', '-v',
        action='store_true',
        help='Create visualization of tree comparisons'
    )
    parser.add_argument(
        '--inspect', '-i',
        action='store_true',
        help='Inspect tree structure and branch length properties'
    )
    
    args = parser.parse_args()
    
    # Validate input files
    if not args.true_tree.exists():
        print(f"Error: True tree file not found: {args.true_tree}")
        sys.exit(1)
    
    # If inspection mode, just inspect trees and exit
    if args.inspect:
        print(f"\n{'='*70}")
        print("TREE STRUCTURE INSPECTION")
        print(f"{'='*70}\n")
        
        # Inspect true tree
        print(f"True tree: {args.true_tree}")
        true_tree = load_tree(args.true_tree)
        true_info = inspect_tree_structure(true_tree)
        print(f"  Leaves: {true_info['num_leaves']}")
        print(f"  Internal nodes: {true_info['num_internal_nodes']}")
        print(f"  Has branch lengths: {true_info['has_branch_lengths']}")
        if true_info['has_branch_lengths']:
            print(f"  All same length: {true_info['all_branch_lengths_same']}")
            stats = true_info['branch_length_stats']
            print(f"  Branch length range: [{stats['min']:.4f}, {stats['max']:.4f}]")
            print(f"  Mean: {stats['mean']:.4f}, Std: {stats['std']:.4f}")
        if true_info['has_polytomies']:
            print(f"  ⚠️  Polytomies: {true_info['polytomies']} (multifurcations detected)")
        else:
            print(f"  ✓ Fully resolved (binary tree)")
        print()
        
        # Inspect inferred trees
        for inferred_tree_path in args.inferred_trees:
            if not inferred_tree_path.exists():
                print(f"Warning: {inferred_tree_path} not found\n")
                continue
            
            print(f"Inferred tree: {inferred_tree_path.name}")
            inferred_tree = load_tree(inferred_tree_path)
            inf_info = inspect_tree_structure(inferred_tree)
            print(f"  Leaves: {inf_info['num_leaves']}")
            print(f"  Internal nodes: {inf_info['num_internal_nodes']}")
            print(f"  Has branch lengths: {inf_info['has_branch_lengths']}")
            if inf_info['has_branch_lengths']:
                print(f"  All same length: {inf_info['all_branch_lengths_same']}")
                stats = inf_info['branch_length_stats']
                print(f"  Branch length range: [{stats['min']:.4f}, {stats['max']:.4f}]")
                print(f"  Mean: {stats['mean']:.4f}, Std: {stats['std']:.4f}")
            if inf_info['has_polytomies']:
                print(f"  ⚠️  Polytomies: {inf_info['polytomies']} (multifurcations detected)")
                print(f"      This means some relationships are UNRESOLVED")
            else:
                print(f"  ✓ Fully resolved (binary tree)")
            print()
        
        print(f"{'='*70}\n")
        return
    
    # Compare each inferred tree with the true tree
    results = []
    
    print(f"\n{'='*70}")
    print("PHYLOGENETIC TREE COMPARISON")
    print(f"{'='*70}")
    print(f"True tree: {args.true_tree}")
    print(f"Comparing {len(args.inferred_trees)} inferred tree(s)...")
    
    # Optional: visualize true tree
    if args.visualize:
        print(f"\nGenerating tree visualizations...")
        true_tree_obj = load_tree(args.true_tree)
        true_tree_vis = args.true_tree.parent / f"{args.true_tree.stem}_visualization.png"
        render_tree(true_tree_obj, true_tree_vis, title="True Phylogenetic Tree")
    
    for inferred_tree_path in args.inferred_trees:
        if not inferred_tree_path.exists():
            print(f"\nWarning: Skipping {inferred_tree_path} (file not found)")
            continue
        
        try:
            metrics = compare_trees(args.true_tree, inferred_tree_path)
            results.append(metrics)
            print(f"\n{metrics}")
            
            # Optional visualization
            if args.visualize:
                inferred_tree = load_tree(inferred_tree_path)
                vis_path = inferred_tree_path.parent / f"{metrics.algorithm_name}_visualization.png"
                render_tree(inferred_tree, vis_path, title=metrics.algorithm_name)
        
        except Exception as e:
            print(f"\nError comparing {inferred_tree_path}: {e}")
            continue
    
    # Summary
    if results:
        print(f"\n{'='*70}")
        print("SUMMARY")
        print(f"{'='*70}")
        
        best_topology = min(results, key=lambda x: x.normalized_rf_distance)
        best_branch_lengths = max(results, key=lambda x: x.branch_length_correlation)
        
        print(f"\nBest topology match: {best_topology.algorithm_name}")
        print(f"  (Normalized RF = {best_topology.normalized_rf_distance:.3f})")
        
        print(f"\nBest branch length correlation: {best_branch_lengths.algorithm_name}")
        print(f"  (Correlation = {best_branch_lengths.branch_length_correlation:.3f})")
        
        # Count perfect matches
        perfect_matches = sum(1 for r in results if r.topology_match)
        if perfect_matches > 0:
            print(f"\n✓ {perfect_matches} algorithm(s) recovered the true topology exactly!")
        else:
            print(f"\n✗ No algorithm recovered the exact topology")
            print(f"  (Best was {best_topology.algorithm_name} with RF = {best_topology.robinson_foulds_distance:.0f})")
    
    # Save report if requested
    if args.output:
        with open(args.output, 'w') as f:
            f.write("Phylogenetic Tree Comparison Report\n")
            f.write("=" * 70 + "\n\n")
            f.write(f"True tree: {args.true_tree}\n")
            f.write(f"Number of comparisons: {len(results)}\n\n")
            
            for metrics in results:
                f.write(str(metrics) + "\n\n")
            
            if results:
                f.write("\nSummary\n")
                f.write("-" * 70 + "\n")
                f.write(f"Best topology: {best_topology.algorithm_name} ")
                f.write(f"(RF = {best_topology.normalized_rf_distance:.3f})\n")
                f.write(f"Best branch lengths: {best_branch_lengths.algorithm_name} ")
                f.write(f"(Corr = {best_branch_lengths.branch_length_correlation:.3f})\n")
        
        print(f"\n✓ Report saved to: {args.output}")
    
    print(f"\n{'='*70}\n")


if __name__ == '__main__':
    main()
